apiVersion: v2
annotations:
  category: icingaweb
name: icingaweb
engine: gotpl

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: 1.x.x

version: 2.7.8
appVersion: "v1.0.0"
